# Generated by Django 5.2.6 on 2025-10-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ecard_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
