# Generated by Django 5.2.6 on 2025-10-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_order_is_paid_order_is_picked'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='token_code',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='order',
            name='token_number',
            field=models.IntegerField(default=0),
        ),
    ]
